#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'garethr-docker'
mod 'jhoblitt-selenium'
mod 'maestrodev-wget'

mod 'puppetlabs-apache'
mod 'puppetlabs-git'
mod 'puppetlabs-java'
mod 'puppetlabs-mysql'

mod 'saz-memcached'
mod 'willdurand-nodejs'

mod 'zivtech-drush'
mod 'zivtech-drupal_php'

# For now we need to install from git.
mod 'zivtech-solr',
  :git => 'https://github.com/zivtech/puppet-drupal-solr.git'

mod 'lliss-packer',
  :git => 'https://github.com/lliss/puppet-packer-1.git'
