#! /usr/bin/env bash

set -e

if [ ! $1 ] ; then
  echo >&2 "You did not specify a name for this solr core."
  echo >&2 ""
  echo >&2 "We suggest using the name of your website."
  echo >&2 ""
  echo >&2 "Usage: create-solr-instance [core name] [config directory]"
  exit 1
fi

NAME=$1

CONF='search_api_solr_8.x-1.0'
SITE_CONF=$(find . -name '6.x' -type d | grep solr | head -n 1)
echo $SITE_CONF

if [[ -n "${SITE_CONF/[ ]*\n/}" ]] ; then
  echo "We are automatically using configuration in \`$SITE_CONF\` to build your $NAME solr instance based on your search_solr_api module version."
  echo "Use the [config directory] parameter in your create-solr-instance command to specify an alternative solr config to use. Example: create-solr-instance drupal /src/solr-config"
    CONF="$SITE_CONF"
fi

sudo -u solr -- /opt/solr/bin/solr create -c "$NAME" -d "$CONF"
echo "A solr core called $NAME has been added with configuration $CONF has been added"
echo "Connect to it at localhost:8983/solr/$NAME"
